# Setup
title:        UX Enthusiast
tagline:      An attempt to share the learning experiences of a passionate front-end engineer.
baseurl:      ""
paginate:     1

# About/contact 
author:
  name:       Anosike Osifo
  url:        http://uxenthusiast.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
include: ['_pages']
excerpt_separator: <!--more-->