# Setup
title:        UX Enthusiast
tagline:      An attempt at learning and building - and sharing experiences in between.
baseurl:      ""
paginate:     1
static_files:  "_assets"

# About/contact
author:
  name:       Anosike Osifo
  url:        http://www.twitter.com/ux_enthusiast

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
include: ['_pages']
excerpt_separator: <!--more-->

syntax-highlighting:
  enabled : true
  css: syntax.css
